server:
  port: 9003

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  threads:
    virtual:
      enabled: true
  datasource:
    #url: jdbc:postgresql://postgresql.cfjzxawtcfzn.ap-south-1.rds.amazonaws.com:5432/postgresql_new
    #username: postgresql
    #password: postgresql
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
cart:
  url: http://localhost:9002/cart